### PR TITLE
add: Product Listing Page

### PR DESCRIPTION
**Pull request by nayyyhaa**
Added product listing page with responsive side-bar.

### CODE REVIEW

**Review by Maianki — APPROVED** [review]
Looks good to merge.

**Review by ApurvaSawant11 — APPROVED** [review]
Looks good to me!

**Comment by anik31** [comment]
Check the color contrast for clear all button. You can make it same as the CTA color or use a lighter shade.

**Comment by nayyyhaa** [comment]
> Check the color contrast for clear all button. You can make it same as the CTA color or use a lighter shade.

@anik31 , I've made the said changes.

**Comment by nayyyhaa** [comment]
Thanks all for reviewing. Merging PR

**Pull request merged**
