### PR TITLE
add: signin + signup page

### PR DESCRIPTION
**Pull request by nayyyhaa**
- Added Sign Up page for new users
- Added Sign In page for existing users

### CODE REVIEW

**Review by BalajiHarinath — APPROVED** [review]
Looks good to me . One suggestion - You can increase the size of the icons in navigation bar.

**Review by vrinda-mahajan — APPROVED** [review]
The code is clean. Good to merge.

**Comment by nayyyhaa** [comment]
> Looks good to me . One suggestion - You can increase the size of the icons in navigation bar.

yes, I'm sending the values from CL.. will update it there. Thanks!

**Comment by nayyyhaa** [comment]
Merging PRs.

**Pull request merged**
